/**
 * MediKiosk — Conversational Intake Screen (v3)
 *
 * Updates:
 *  - Supports dynamic options generated by LLM
 *  - Adds a free text input for typing responses
 *  - Displays conversation history
 *  - Displays section summary
 */

import { useEffect, useCallback, useRef, useState } from 'react';
import { Mic, MicOff, TriangleAlert, SkipForward, Volume2, VolumeX, Send } from 'lucide-react';
import { AbstractOrb } from '../components/AbstractOrb';
import type { OrbState } from '../components/AbstractOrb';
import type { UIInstruction } from '../hooks/useConversation';
import { useSarvamSTT } from '../hooks/useSarvamSTT';
import { useSarvamTTS } from '../hooks/useSarvamTTS';

interface Props {
  ui: UIInstruction;
  orbState: OrbState;
  isProcessing: boolean;
  onTap: (value: string) => void;
  onVoice: (transcript: string, detectedLanguage?: string) => void;
  onSkip: () => void;
  onBack: () => void;
  onRedflag: () => void;
}

export function Screen3_ConversationalIntake({
  ui,
  orbState,
  isProcessing,
  onTap,
  onVoice,
  onSkip,
  onBack,
  onRedflag,
}: Props) {
  const { speak, stop: stopTTS, isSpeaking } = useSarvamTTS();
  const [inputText, setInputText] = useState('');

  // Track the last prompt to avoid re-speaking the same one
  const lastSpokenPromptRef = useRef<string>('');

  // STT with direct callback
  const handleSTTResult = useCallback((result: { transcript: string; language_code: string }) => {
    if (result.transcript) {
      console.log('[Screen3] STT result received:', result.transcript);
      onVoice(result.transcript, result.language_code);
    }
  }, [onVoice]);

  const { isRecording, startRecording, stopRecording, error: sttError, audioLevel } =
    useSarvamSTT(ui.language || 'hi-IN', handleSTTResult);

  // Auto-TTS: speak the prompt whenever a new one arrives
  useEffect(() => {
    if (
      ui.prompt &&
      !isProcessing &&
      ui.prompt !== lastSpokenPromptRef.current
    ) {
      lastSpokenPromptRef.current = ui.prompt;
      const textToSpeak = ui.ack ? `${ui.ack}. ${ui.prompt}` : ui.prompt;
      speak(textToSpeak, ui.language || 'hi-IN');
    }
  }, [ui.prompt, ui.ack, ui.language, isProcessing, speak]);

  const handleMicPress = useCallback(async (e: React.MouseEvent | React.TouchEvent) => {
    stopTTS();
    await startRecording(e);
  }, [startRecording, stopTTS]);

  const handleMicRelease = useCallback((e: React.MouseEvent | React.TouchEvent) => {
    stopRecording(e);
  }, [stopRecording]);

  const handleOptionTap = useCallback((opt: { label: string; value?: string }) => {
    stopTTS();
    const backendValue = opt.value || opt.label;
    onTap(backendValue);
  }, [onTap, stopTTS]);

  const handleTextSubmit = useCallback((e: React.FormEvent) => {
    e.preventDefault();
    if (!inputText.trim()) return;
    stopTTS();
    onVoice(inputText.trim(), ui.language || 'en-IN');
    setInputText('');
  }, [inputText, stopTTS, onVoice, ui.language]);

  const progress = ui.progress;
  const effectiveOrbState: OrbState = isRecording ? 'listening' : isSpeaking ? 'speaking' : orbState;
  const micRingOpacity = isRecording ? Math.min(audioLevel * 2, 1) : 0;

  return (
    <div className="flex flex-1 w-full max-w-6xl mx-auto h-full overflow-hidden">
      
      {/* Left Column: Chat History & Summary */}
      <div className="hidden lg:flex flex-col w-1/3 bg-gray-50 border-r border-gray-200 p-6 overflow-y-auto">
        <h3 className="text-sm font-bold text-gray-400 uppercase tracking-wider mb-4">Summary So Far</h3>
        <div className="bg-white p-4 rounded-xl border border-gray-100 shadow-sm mb-6 text-sm text-gray-700">
          {ui.section_summary || 'Waiting for information...'}
        </div>
        
        <h3 className="text-sm font-bold text-gray-400 uppercase tracking-wider mb-4">Conversation</h3>
        <div className="flex flex-col gap-3">
          {(ui.conversation_history || []).map((msg, idx) => (
            <div key={idx} className={`p-3 rounded-lg text-sm max-w-[85%] ${
              msg.role === 'assistant' 
                ? 'bg-blue-50 text-blue-800 self-start border border-blue-100' 
                : 'bg-white text-gray-700 self-end border border-gray-200'
            }`}>
              {msg.content}
            </div>
          ))}
        </div>
      </div>

      {/* Right Column: Interaction */}
      <div className="flex flex-col flex-1 items-center p-6 sm:p-10 text-center overflow-y-auto">
        
        {/* Section Label + Progress */}
        <div className="mb-2 flex items-center gap-3 flex-wrap justify-center">
          <span className="text-sm font-semibold tracking-wider text-blue-600 uppercase bg-blue-50 px-4 py-1.5 rounded-full">
            {ui.section_label || ui.macro_state}
          </span>
          {ui.language && ui.language !== 'en-IN' && (
            <span className="text-xs text-emerald-600 bg-emerald-50 border border-emerald-200 px-3 py-1 rounded-full">
              🌐 {ui.language}
            </span>
          )}
        </div>

        {progress && (
          <div className="w-full max-w-xs mb-6">
            <div className="flex justify-between text-xs text-gray-400 mb-1">
              <span>{(progress as any).label || `${progress.done} of ${progress.total}`}</span>
              <span>{(progress as any).percent ?? Math.round((progress.done / Math.max(progress.total, 1)) * 100)}%</span>
            </div>
            <div className="w-full bg-gray-100 rounded-full h-2">
              <div
                className="bg-blue-500 h-2 rounded-full transition-all duration-500"
                style={{ width: `${(progress as any).percent ?? (progress.done / Math.max(progress.total, 1)) * 100}%` }}
              />
            </div>
          </div>
        )}

        {ui.ack && (
          <p className="text-sm text-teal-600 italic mb-2 max-w-md">{ui.ack}</p>
        )}

        {/* The Central Animated Orb */}
        <div className="my-8 relative">
          <AbstractOrb interactionState={effectiveOrbState} />
          {isSpeaking && (
            <div className="absolute -bottom-6 left-1/2 -translate-x-1/2 flex items-center gap-1 text-xs text-blue-500">
              <Volume2 className="w-3 h-3 animate-pulse" />
              <span>Speaking...</span>
            </div>
          )}
          {isRecording && (
            <div className="absolute -bottom-6 left-1/2 -translate-x-1/2 flex items-center gap-1 text-xs text-red-500">
              <span className="w-2 h-2 bg-red-500 rounded-full animate-ping inline-block" />
              <span>Listening...</span>
            </div>
          )}
        </div>

        {/* LLM-phrased Prompt */}
        <h2 className="text-2xl font-semibold text-gray-800 mb-8 min-h-[2rem]">
          {isProcessing ? (
            <span className="text-blue-400 animate-pulse">Thinking...</span>
          ) : (
            ui.prompt
          )}
        </h2>

        {sttError && (
          <p className="text-xs text-red-400 mb-4">⚠ {sttError}</p>
        )}

        {/* Dynamic Options */}
        {ui.options && ui.options.length > 0 && (
          <div className="grid grid-cols-2 sm:grid-cols-3 gap-3 w-full max-w-2xl mb-8">
            {ui.options.map((opt, idx) => (
              <button
                key={idx}
                id={`option-${idx}`}
                onClick={() => handleOptionTap(opt as any)}
                disabled={isProcessing || isRecording}
                className="flex flex-col items-center justify-center gap-2 py-4 px-4 bg-white border border-gray-200 rounded-2xl hover:border-blue-400 hover:shadow-md hover:bg-blue-50/30 transition-all text-gray-700 font-medium disabled:opacity-50 disabled:cursor-wait"
              >
                {opt.label}
              </button>
            ))}
          </div>
        )}

        {/* Bottom Action Bar */}
        <div className="mt-auto flex flex-col w-full max-w-2xl gap-4">
          
          {/* Text input form */}
          <form onSubmit={handleTextSubmit} className="flex w-full gap-2 relative">
            <input 
              type="text" 
              value={inputText}
              onChange={(e) => setInputText(e.target.value)}
              disabled={isProcessing || isRecording}
              placeholder="Type your response here..."
              className="flex-1 rounded-full border border-gray-300 px-6 py-3 focus:outline-none focus:border-blue-500 focus:ring-2 focus:ring-blue-200 disabled:opacity-50"
            />
            <button 
              type="submit" 
              disabled={isProcessing || isRecording || !inputText.trim()}
              className="absolute right-2 top-1.5 p-2 bg-blue-100 text-blue-600 rounded-full hover:bg-blue-200 disabled:opacity-50"
            >
              <Send className="w-5 h-5" />
            </button>
          </form>

          <div className="flex items-center justify-between border-t border-gray-100 pt-4">
            <button
              id="btn-back"
              onClick={onBack}
              className="px-4 py-2 rounded-xl font-medium text-gray-500 hover:bg-gray-100"
            >
              Back
            </button>

            <div className="flex items-center gap-3">
              <button
                id="btn-tts-toggle"
                type="button"
                onClick={() => isSpeaking ? stopTTS() : speak(ui.prompt || '', ui.language || 'hi-IN')}
                title={isSpeaking ? 'Stop speaking' : 'Replay prompt'}
                className="p-3 rounded-full text-blue-400 hover:bg-blue-50 transition-all"
              >
                {isSpeaking ? <VolumeX className="w-5 h-5" /> : <Volume2 className="w-5 h-5" />}
              </button>

              <div className="relative">
                <div
                  className="absolute inset-0 rounded-full bg-red-400 transition-opacity duration-100"
                  style={{
                    opacity: micRingOpacity * 0.3,
                    transform: `scale(${1 + audioLevel * 0.3})`,
                    transition: 'transform 0.1s, opacity 0.1s',
                  }}
                />
                <button
                  id="btn-mic"
                  type="button"
                  onMouseDown={handleMicPress}
                  onMouseUp={handleMicRelease}
                  onTouchStart={handleMicPress}
                  onTouchEnd={handleMicRelease}
                  onTouchCancel={handleMicRelease}
                  disabled={isProcessing}
                  className={`relative flex items-center gap-3 px-8 py-3 rounded-full font-bold text-white transition-all transform active:scale-95 shadow-lg ${
                    isRecording
                      ? 'bg-red-500 shadow-red-200'
                      : 'bg-blue-600 shadow-blue-200 hover:bg-blue-700'
                  } disabled:opacity-50`}
                >
                  {isRecording ? <MicOff className="w-5 h-5" /> : <Mic className="w-5 h-5" />}
                  {isRecording ? 'Release to Send' : 'Hold to Speak'}
                </button>
              </div>
            </div>

            <div className="flex gap-2">
              {ui.can_skip && (
                <button
                  id="btn-skip"
                  type="button"
                  onClick={onSkip}
                  className="p-3 rounded-xl font-medium text-gray-400 hover:bg-gray-50 flex items-center justify-center"
                  title="Skip this question"
                >
                  <SkipForward className="w-5 h-5" />
                </button>
              )}
              <button
                id="btn-redflag"
                type="button"
                onClick={onRedflag}
                className="p-3 rounded-xl font-medium text-red-500 hover:bg-red-50 flex items-center justify-center"
                title="Simulate Red Flag"
              >
                <TriangleAlert className="w-5 h-5" />
              </button>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
